### ISSUE TITLE
Small problems (XH-DEPRECATED and <p>Tag)

### ISSUE THREAD

**Issue by lck-git** [cmb69/codeeditor_xh#13]
See https://cmsimpleforum.com/viewtopic.php?f=42&t=16338&p=76172#p76172

**Comment by cmb69** [comment]
The `initvar()` calls are already removed as of 4f7092cd8025615789710845f219a3632bbb9509. I need to do a new release. :)

> Bin ich in der Quelltextanzeige und klicke OK, so fügt der Codeeditor einen p-Tag ganz am Anfang der Seite vor H1 ein:

````.html
<p> </p>
<h1>Content</h1>
````

I can reproduce with TinyMCE 4, but not with TinyMCE 5. Same for you? And actually, this is not a Codeeditor_XH issue, but rather a TinyMCE/Codemirror (plugin) issue.

**Comment by lck-git** [comment]
> I can reproduce with TinyMCE 4, but not with TinyMCE 5. Same for you?

Doch mit'm TinyMCE 5 auch.
Bestehende Seite > Bearbeiten > Ansicht, Quelltext > auf OK. Nochmal Ansicht > Quelltext. Da ist es.
Man kann es aber nicht speichern, erst wenn man noch etwas anderes am Text verändert.

> And actually, this is not a Codeeditor_XH issue, but rather a TinyMCE/Codemirror (plugin) issue.
Ok, dann sollten wir das weitergeben an @manu.

**Comment by lck-git** [comment]
> Ok, dann sollten wir das weitergeben an @manu.

Und auch gleich die Lösung des Problems, die gibt's [hier](https://gitlab.com/tinymce-plugins/tinymce-codemirror/-/issues/37#note_198107008).

> Hi ! I have the same problem. I use TinyMCE 4.9.3 - CodeMirror 5.44.0 - Firefox 65. Any idea to solve that problem ? Thanx !
> 
> Edit : Well, I think I solved the problem with a little conf of TynyMCE. I added thoses lines :
> 
> ```
> entity_encoding: "raw",
> force_p_newlines : true,
> forced_root_block : "",
> ```
> 
> I don't know if "raw" is required, but I didn't want HTML entities in my code, so it'just good for me. Hope this will help !

`"entity_encoding": "raw",` gibt es schon in der init_dropdown-codemirror.json muss also nur noch folgendes ergänzt werden.
`  "force_p_newlines" : true,
  "forced_root_block" : "",  `

Getestet, funktioniert! Kein <p> Tag mehr am Anfang 🙂

**Comment by cmb69** [comment]
Danke für die Recherche und das Weitergeben an XH. Ich schließe dieses Ticket dann mal.
