### ISSUE TITLE
XH-DEPRECATED: Function initvar() is deprecated

### ISSUE THREAD

**Issue by lck-git** [cmb69/codeeditor_xh#8]
To avoid debug mode messages, delete these 3 lines.
https://github.com/cmb69/codeeditor_xh/blob/dd38942401ac19ee77703edef5687d5adcc9bf5a/classes/Controller.php#L66-L68

*Nachtrag: Sehe gerade das Issue gibt es schon https://github.com/cmb69/codeeditor_xh/issues/6.

**Comment by cmb69** [comment]
> *Nachtrag: Sehe gerade das Issue gibt es schon #6.

Trotzdem danke fürs melden! :)
